#!/usr/bin/env python

# Copyright 2015 Donal Heidenblad
#
# This file is part of RepoAnalY.
#
# RepoAnalY is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# RepoAnalY is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RepoAnalY.  If not, see <http://www.gnu.org/licenses/>.
#
# Authors : Donal Heidenblad <dheidenb@umd.edu>


"""
Point of entry to the main module of the program.

@author:       Donal Heidenblad
@copyright:    2015 Donal Heidenblad
@license:      GNU GPL version 3 or any later version
@contact:      dheidenb@umd.edu
"""

import sys
import pyrepoanaly.main

if __name__ == "__main__":
    try:
        retval = pyrepoanaly.main.main (sys.argv[1:])
        sys.exit (retval)
    except KeyboardInterrupt:
        print "\n\nReceived Ctrl-C or other break signal. Exiting."
        sys.exit (0)


